service-order-customer:
  url: ${SERVICE_ORDER_CUSTOMER_URL:http://localhost:8089}
service-models:
  url: ${SERVICE_MODELS_URL:http://localhost:8088}
esb-service:
  url: ${SERVICE_MODELS_URL:http://localhost:8090}
server:
  port: 8088
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
vpn:
  kafka:
    bootstrap-servers: localhost:9092
    product:
      batchConcurrency: 3
#      group: group
spring:
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always # Spring Boot >=v2.5.0
      platform: h2 # Spring Boot <v2.5.0
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db?useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: user
    password: password
#    initialization-mode: always # Spring Boot <v2.5.0
#    platform: h2 # Spring Boot <v2.5.0
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    open-in-view: false
#    generate-ddl: true
    defer-datasource-initialization: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    validateOnMigrate: false
    locations: "classpath:db/migration"
  data:
    mongodb:
#      authentication-database: admin
#      username: test
#      password: test
      database: mongo_test_db
#      port: 27017
#      host: 127.0.0.1
      uri: mongodb://test:test@127.0.0.1:27017/mongo_test_db?authSource=admin
      uuid-representation: standard
      repositories:
        enabled=true:
  spring:
    h2:
      console:
        enabled: true
        path: /h2-console
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
logging:
  file:
    path: ${LOGGER_FOLDER_LOCATION:log}